#!/bin/bash

Lib=${Lib:-.}
export Var=$HOME/opt/awk/var
export Tmp=$HOME/opt/awk/tmp

mkdir -p $Var $Tmp

defs() { cat - | gawk  '{
    n=split($3,a,",") 
    rhs=""
    lhs= ""$2"\\([a-zA-Z0-9_\"]*\\)"
    for(i=1;i<=n;i++)     
      rhs = (rhs ? rhs "," : "") a[i] "\\1"
     print "-e s/"lhs"/"rhs"/g"
   } '
}

for d in . $Lib $AWKPATH; do
    for old in $d/*.awk; do
	echo $old
	new=$Var/$(basename $old)
	if true; then #[ "$old" -nt "$new" ]; then
	    subs1='s/:\([_0-9a-zA-Z]*\)/["\1"]/g'
	    subs2=$(grep '^#def' $old | defs)
	    sed -e $subs1 $subs2  $old > $new
        fi
    done
done

#alias Run="AWKPATH=$Var pgawk --dump-variables=$Tmp/awkvars.out --profile=$Tmp/awkprof.out "

    
#$Run "$*"
